import { Product } from '@/types'

export const products: Product[] = [
  {
    id: 'nike-mercurial-vapor-16-elite',
    name: 'Mercurial Vapor 16 Elite FG',
    brand: 'Nike',
    price: 22499,
    originalPrice: 25999,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
    ],
    category: 'football-boots',
    description: 'Explosive speed on firm ground. Kylian Mbappé\'s signature boot.',
    longDescription: 'The Nike Mercurial Vapor 16 Elite is built for speed. The Vaporposite upper wraps your foot like a second skin, while the carbon fiber plate provides explosive energy return on every touch. Designed for the fastest players on the pitch.',
    sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11'],
    colors: ['Volt/Black', 'Crimson/White'],
    inStock: true,
    featured: true,
    isNew: true,
    rating: 4.9,
    reviewCount: 128,
    tags: ['speed', 'firm ground', 'nike', 'elite'],
    createdAt: '2025-01-01',
  },
  {
    id: 'adidas-predator-elite-fg',
    name: 'Predator Elite FG',
    brand: 'Adidas',
    price: 19999,
    originalPrice: 23499,
    images: [
      'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=800',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
    ],
    category: 'football-boots',
    description: 'Total control. The boot for playmakers.',
    longDescription: 'The Adidas Predator Elite delivers unmatched ball control thanks to its rubber zone texture zones. The Primeknit upper provides a sock-like fit while the carbon fiber outsole drives explosive acceleration.',
    sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '11'],
    colors: ['Core Black/White', 'Solar Red'],
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 94,
    tags: ['control', 'firm ground', 'adidas', 'elite'],
    createdAt: '2025-01-01',
  },
  {
    id: 'puma-future-7-ultimate-fg',
    name: 'Future 7 Ultimate FG/AG',
    brand: 'Puma',
    price: 17999,
    originalPrice: 20499,
    images: [
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800',
    ],
    category: 'football-boots',
    description: 'Adaptive fit for unpredictable players.',
    longDescription: 'The Puma Future 7 Ultimate features the revolutionary FUZIONFIT+ compression band for an adaptive, glove-like fit. The GripControl Pro texture gives you exceptional ball grip in any condition.',
    sizes: ['6', '7', '7.5', '8', '8.5', '9', '9.5', '10', '11'],
    colors: ['Yellow Alert/Black', 'Sunset Glow'],
    inStock: true,
    featured: false,
    isNew: true,
    rating: 4.7,
    reviewCount: 67,
    tags: ['adaptive', 'firm ground', 'puma'],
    createdAt: '2025-01-01',
  },
  {
    id: 'nike-phantom-gx2-elite-fg',
    name: 'Phantom GX II Elite FG',
    brand: 'Nike',
    price: 21499,
    originalPrice: 24999,
    images: [
      'https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?w=800',
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1511556820780-d912e42b4980?w=800',
    ],
    category: 'football-boots',
    description: 'Precision passing. Deadly finishing.',
    longDescription: 'The Nike Phantom GX II Elite is engineered for the playmaker. Ghost Lace technology moves the lace system to the side for a clean striking zone, while the All Conditions Control (ACC) texture ensures consistent performance in wet or dry conditions.',
    sizes: ['6', '6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '10.5', '11'],
    colors: ['Metallic Silver/Black', 'Bright Crimson'],
    inStock: true,
    featured: true,
    rating: 4.8,
    reviewCount: 112,
    tags: ['precision', 'firm ground', 'nike'],
    createdAt: '2025-01-01',
  },
  {
    id: 'adidas-x-crazyfast-elite-fg',
    name: 'X Crazyfast.1 Elite FG',
    brand: 'Adidas',
    price: 18999,
    originalPrice: 22499,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
    ],
    category: 'football-boots',
    description: 'Lightest boot in Adidas history.',
    longDescription: 'The Adidas X Crazyfast.1 is the lightest boot Adidas has ever made. The revolutionary Carbitex outsole is both ultra-light and incredibly stiff for maximum energy transfer, while the Cageless upper delivers a barefoot-like touch.',
    sizes: ['6.5', '7', '7.5', '8', '8.5', '9', '9.5', '10', '11'],
    colors: ['Cloud White/Black', 'Solar Orange'],
    inStock: true,
    featured: false,
    rating: 4.7,
    reviewCount: 83,
    tags: ['speed', 'lightweight', 'adidas'],
    createdAt: '2025-01-01',
  },
  {
    id: 'nike-mercurial-superfly-9-elite-tf',
    name: 'Mercurial Superfly 9 Elite TF',
    brand: 'Nike',
    price: 15499,
    originalPrice: 17999,
    images: [
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800',
    ],
    category: 'turf',
    description: 'Dominate turf surfaces with Superfly speed.',
    longDescription: 'The Mercurial Superfly 9 Elite TF is engineered for turf surfaces. The multi-directional turf studs provide excellent traction while the Dynamic Fit collar locks your foot in for explosive sprints.',
    sizes: ['6', '7', '7.5', '8', '8.5', '9', '9.5', '10', '11'],
    colors: ['Volt/Black', 'Bright Crimson/White'],
    inStock: true,
    featured: false,
    rating: 4.6,
    reviewCount: 54,
    tags: ['turf', 'speed', 'nike'],
    createdAt: '2025-01-01',
  },
]

export const categories = [
  { id: 'boots',            label: 'Boots',             description: 'Football boots, FG/AG/TF/IC' },
  { id: 'jerseys-jackets',  label: 'Jerseys & Jackets',  description: 'Kits, training tops, jackets' },
  { id: 'balls',            label: 'Balls',              description: 'Match and training balls' },
  { id: 'gloves',           label: 'Gloves',             description: 'Goalkeeper and outfield gloves' },
  { id: 'essential',         label: 'Essential',           description: 'Essential Gear' },
]

export const brands = ['Nike', 'Adidas', 'Puma', 'New Balance', 'Mizuno']
